version: "3.8"

services:
  development:
    container_name: shortener-dev
    build:
      context: .
      target: development
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/shortener
    volumes:
      - .:/usr/src/app 
    depends_on: 
      - mongodb

  mongodb:
    container_name: shortener-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
